version: "3.7"

services:
  relicario-api:
    container_name: relicario-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/app"
    environment:
      - PORT=3700
    ports:
      - 3700:3700
