version: "3.7"

services:
  relicario-api:
    container_name: relicario-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 2021:2021
