version: "3.7"

services:
  relicario-api:
    container_name: relicario-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/app"
    environment:
      - PORT=8080
    ports:
      - 8080:8080
