name: cicd-backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build project
        run: yarn build

      - shell: bash
        if: github.ref == 'refs/heads/main'
        name: Create SSH deployment key
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: ./scripts/deploy.sh

      - name: Deployment | Copy file via ssh
        if: github.ref == 'refs/heads/main'
        run: scp -r /home/runner/relicario-api/dist backend@josematias.dev:/home/backend/
