name: cicd-backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Stop PM2
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'pm2 stop relicario-api'
        if: ${{failure()}}

      - name: Deploy with rsync
        run: |
          rsync -rav ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/backend/dist/
          rsync -rav ./package.json ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/backend/

      - name: Install dependencies on server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'yarn'

      - name: Start PM2
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd backend && yarn restart:prod'
